apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pvc-access-role
  namespace: sn-labs-nadeenelsaye  # Make sure this is your target namespace
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "delete"]
